.PHONY: all
all:
	$(MAKE) -C singlepage
	$(MAKE) -C multipage
	$(MAKE) -C singledl
	$(MAKE) -C multidl

.PHONY: pristine
pristine:
	$(MAKE) -C singlepage pristine
	$(MAKE) -C multipage pristine
	$(MAKE) -C singledl pristine
	$(MAKE) -C multidl pristine

.PHONY: clean
clean:
	$(MAKE) -C singlepage clean
	$(MAKE) -C multipage clean
	$(MAKE) -C singledl clean
	$(MAKE) -C multidl clean

