TARGETS=broadcaster client getip ghbn ieee754 listener pack pack2 \
	select selectserver server showip talker

CC=gcc
CCOPTS=-Wall -Wextra

.PHONY: all clean pristine

all: $(TARGETS)

clean:
	rm -f $(TARGETS)

pristine: clean

%: %.c
	$(CC) $(CCOPTS) -o $@ $<
