TITLE="Beej's Guide to Network Programming"
SUBTITLE="Using Internet Sockets"
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v3.2.11, Copyright © July 8, 2025"

GUIDE_ID=bgnet
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.svg)
EPUB_SVGS=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make

