TITLE="Beej's Guide to Network Programming"
SUBTITLE="Using Internet Sockets"
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v3.1.12, Copyright © July 17, 2024"

GUIDE_ID=bgnet
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make

