#!/bin/sh

#
# Create the yaml metadata files for the various book formats
#

if [ $# -ne 2 ]; then
    printf "usage: %s semver date\n" $0 1>&2
    printf "       %s 3.0.21 \"June 8, 2016\"\n" $0 1>&2
    exit 1
fi

semver=$1
copydate=$2

function gen {
    local filename=$1
    local sided=$2
    local paper=$3

    cat <<_EOF_ > ${filename}
---
title: Beej's Guide to Network Programming
subtitle: Using Internet Sockets
author: Brian "Beej Jorgensen" Hall
date: v${semver}, Copyright © ${copydate}
classoption: ${sided}
papersize: ${paper}
---
_EOF_
}

cat <<_EOF_ > meta-html.yaml
---
title: Beej's Guide to Network Programming
subtitle: Using Internet Sockets
author: Brian "Beej Jorgensen" Hall
date: v${semver}, Copyright © ${copydate}
---
_EOF_

cat <<_EOF_ > meta-crownquarto-2.yaml
---
title: Beej's Guide to Network Programming
subtitle: Using Internet Sockets
author: Brian "Beej Jorgensen" Hall
date: v${semver}, Copyright © ${copydate}
classoption: twoside
geometry: "paperwidth=7.44in,paperheight=9.68in"
---
_EOF_

gen meta-letter-1.yaml oneside letter
gen meta-letter-2.yaml twoside letter

gen meta-a4-1.yaml oneside a4
gen meta-a4-2.yaml twoside a4
